# Generated by Django 4.1.7 on 2023-03-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date upload'),
        ),
    ]
