# Generated by Django 4.1.7 on 2023-03-09 15:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Kitchen', 'Kitchen'), ('AC', 'AC'), ('Private pool', 'Private pool'), ('Shared pool', 'Shared pool'), ('Wi-Fi', 'Wi-Fi'), ('Shower', 'Shower'), ('Bathtub', 'Bathtub'), ('Cleaning service', 'Cleaning service'), ('TV', 'TV'), ('Parking area', 'Parking area')], max_length=244, null=True, verbose_name='Amenities'),
        ),
    ]
