# Generated by Django 4.1.7 on 2023-03-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='images',
        ),
        migrations.AddField(
            model_name='apartment',
            name='images',
            field=models.ManyToManyField(blank=True, to='appart.image', verbose_name='Images'),
        ),
    ]
