# Generated by Django 4.1.7 on 2023-03-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0002_apartment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessageForAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Write your message for all users in VillaBot')),
            ],
        ),
    ]
