# Generated by Django 4.1.7 on 2023-03-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0002_alter_apartment_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price_usd',
            field=models.BigIntegerField(null=True, verbose_name='Price in USD'),
        ),
    ]
