# Generated by Django 4.1.7 on 2023-03-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0002_remove_apartment_images_apartment_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='description',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Description'),
        ),
    ]
