# Generated by Django 4.1.7 on 2023-03-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0003_sendmessageforall'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessageforall',
            name='images',
            field=models.ManyToManyField(blank=True, to='appart.image', verbose_name='Images'),
        ),
    ]
