# Generated by Django 4.1.7 on 2023-03-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0004_alter_apartment_price_rup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='agent_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Agent Name'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='agent_whats_up',
            field=models.URLField(blank=True, null=True, verbose_name='Agent Whats App'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price_rup',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Price in Rupee'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price_usd',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Price in USD'),
        ),
        migrations.AlterField(
            model_name='rentuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram Username'),
        ),
    ]
