# Generated by Django 4.1.7 on 2023-03-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0004_sendmessageforall_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessageForChooseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Write your message for all users in VillaBot')),
                ('images', models.ManyToManyField(blank=True, to='appart.image', verbose_name='Images')),
                ('users', models.ManyToManyField(to='appart.rentuser', verbose_name='Choose users')),
            ],
        ),
    ]
