# Generated by Django 4.1.7 on 2023-03-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0005_sendmessageforchooseuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessageforall',
            name='images',
        ),
        migrations.RemoveField(
            model_name='sendmessageforchooseuser',
            name='images',
        ),
        migrations.AlterField(
            model_name='sendmessageforchooseuser',
            name='text',
            field=models.TextField(verbose_name='Write your message for selected users in VillaBot'),
        ),
        migrations.AlterField(
            model_name='sendmessageforchooseuser',
            name='users',
            field=models.ManyToManyField(to='appart.rentuser', verbose_name='Select users'),
        ),
        migrations.AddField(
            model_name='sendmessageforall',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='SendMessage/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='sendmessageforchooseuser',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='SendMessage/', verbose_name='Image'),
        ),
    ]
