# Generated by Django 4.1.7 on 2023-03-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0005_alter_apartment_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentuser',
            name='default_lang',
            field=models.CharField(choices=[('EN', 'English'), ('RU', 'Русский'), ('IN', 'Indonesian')], default=None, max_length=2, verbose_name='Default language'),
        ),
    ]
