# Generated by Django 4.1.7 on 2023-03-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0006_rentuser_default_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentuser',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Phone Number'),
        ),
    ]
