# Generated by Django 4.1.7 on 2023-03-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0006_remove_sendmessageforall_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessageforall',
            name='images',
        ),
        migrations.RemoveField(
            model_name='sendmessageforchooseuser',
            name='images',
        ),
        migrations.AlterField(
            model_name='sendmessageforchooseuser',
            name='text',
            field=models.TextField(verbose_name='Write your message for all users in VillaBot'),
        ),
        migrations.AlterField(
            model_name='sendmessageforchooseuser',
            name='users',
            field=models.ManyToManyField(to='appart.rentuser', verbose_name='Choose users'),
        ),
        migrations.AddField(
            model_name='sendmessageforall',
            name='images',
            field=models.ManyToManyField(blank=True, to='appart.image', verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='sendmessageforchooseuser',
            name='images',
            field=models.ManyToManyField(blank=True, to='appart.image', verbose_name='Images'),
        ),
    ]
