# Generated by Django 4.1.7 on 2023-03-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0007_remove_sendmessageforall_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessageforall',
            name='images',
        ),
        migrations.RemoveField(
            model_name='sendmessageforchooseuser',
            name='images',
        ),
        migrations.AlterField(
            model_name='sendmessageforchooseuser',
            name='text',
            field=models.TextField(verbose_name='Write your message for selected user in VillaBot'),
        ),
        migrations.RemoveField(
            model_name='sendmessageforchooseuser',
            name='users',
        ),
        migrations.AddField(
            model_name='sendmessageforall',
            name='images',
            field=models.ImageField(blank=True, upload_to='SendMessage/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='sendmessageforchooseuser',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='SendMessage/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='sendmessageforchooseuser',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appart.rentuser', verbose_name='Select user'),
        ),
    ]
