# Generated by Django 4.1.7 on 2023-03-13 09:50

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0007_rentuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='apartment_images', verbose_name='Image'),
        ),
    ]
