# Generated by Django 4.1.7 on 2023-03-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0008_alter_apartment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='image',
        ),
    ]
