# Generated by Django 4.1.7 on 2023-03-30 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appart', '0008_remove_sendmessageforall_images_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'permissions': [('can_edit_owned_apartment', 'Can edit owned apartment'), ('can_delete_owned_apartment', 'Can delete owned apartment')]},
        ),
        migrations.AddField(
            model_name='apartment',
            name='author',
            field=models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
