# Generated by Django 4.1.7 on 2023-04-01 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('daily', models.IntegerField(blank=True, default=0, null=True, verbose_name='New ads per day')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='All ads')),
            ],
        ),
        migrations.CreateModel(
            name='CommonStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('link', models.IntegerField(blank=True, default=0, null=True, verbose_name='Followed by bot link')),
                ('cmd_start', models.IntegerField(blank=True, default=0, null=True, verbose_name='Command Start')),
                ('start_register', models.IntegerField(blank=True, default=0, null=True, verbose_name='Started registration')),
                ('finish_register', models.IntegerField(blank=True, default=0, null=True, verbose_name='Finished registration')),
                ('contact', models.IntegerField(blank=True, default=0, null=True, verbose_name='Click on the contact button')),
                ('subscribe', models.IntegerField(blank=True, default=0, null=True, verbose_name='Subscribed')),
                ('find', models.IntegerField(blank=True, default=0, null=True, verbose_name='Started searching')),
                ('search', models.IntegerField(blank=True, default=0, null=True, verbose_name='Started executing the request')),
            ],
        ),
        migrations.CreateModel(
            name='LocationStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('index', models.TextField(blank=True, null=True, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRUPStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first', models.IntegerField(blank=True, default=0, null=True, verbose_name='less than 10 mln')),
                ('second', models.IntegerField(blank=True, default=0, null=True, verbose_name='10 mln - 20 mln')),
                ('third', models.IntegerField(blank=True, default=0, null=True, verbose_name='20 mln - 30 mln')),
                ('fourth', models.IntegerField(blank=True, default=0, null=True, verbose_name='30 mln - 40 mln')),
                ('fifth', models.IntegerField(blank=True, default=0, null=True, verbose_name='40 mln - 50 mln')),
                ('sixth', models.IntegerField(blank=True, default=0, null=True, verbose_name='more than 50 mln')),
            ],
        ),
        migrations.CreateModel(
            name='PriceUSDStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first', models.IntegerField(blank=True, default=0, null=True, verbose_name='Less than 650')),
                ('second', models.IntegerField(blank=True, default=0, null=True, verbose_name='650 - 1300$')),
                ('third', models.IntegerField(blank=True, default=0, null=True, verbose_name='1300 - 1950$')),
                ('fourth', models.IntegerField(blank=True, default=0, null=True, verbose_name='1950 - 2600$')),
                ('fifth', models.IntegerField(blank=True, default=0, null=True, verbose_name='2600 - 3250$')),
                ('sixth', models.IntegerField(blank=True, default=0, null=True, verbose_name='more than 3250$')),
            ],
        ),
        migrations.CreateModel(
            name='ApartStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Views')),
                ('favorite', models.IntegerField(blank=True, default=0, null=True, verbose_name='Add to favorite')),
                ('contact', models.IntegerField(blank=True, default=0, null=True, verbose_name='View agent contact')),
                ('find_date', models.DateTimeField(blank=True, null=True, verbose_name='Last view in find')),
                ('favorite_date', models.DateTimeField(blank=True, null=True, verbose_name='Last add in favorite')),
                ('apart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appart.apartment', verbose_name='Date upload and Unique ID apartment')),
            ],
        ),
    ]
