# Generated by Django 4.1.7 on 2023-03-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('link', models.IntegerField(blank=True, default=0, null=True, verbose_name='Followed by bot link')),
                ('cmd_start', models.IntegerField(blank=True, default=0, null=True, verbose_name='Command Start')),
                ('start_register', models.IntegerField(blank=True, default=0, null=True, verbose_name='Started registration')),
                ('finish_register', models.IntegerField(blank=True, default=0, null=True, verbose_name='Finished registration')),
                ('contact', models.IntegerField(blank=True, default=0, null=True, verbose_name='Click on the contact button')),
                ('contact_link', models.IntegerField(blank=True, default=0, null=True, verbose_name='Followed by agent link')),
                ('subscribe', models.IntegerField(blank=True, default=0, null=True, verbose_name='Subscribed')),
            ],
        ),
    ]
