# Generated by Django 4.1.7 on 2023-03-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='unique_users',
            field=models.IntegerField(blank=True, null=True, verbose_name='Unique Users'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='users_finsh',
            field=models.IntegerField(blank=True, null=True, verbose_name='Communication with an agent'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='users_pay',
            field=models.IntegerField(blank=True, null=True, verbose_name='Made a payment'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='users_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Command Start'),
        ),
    ]
