# Generated by Django 4.1.7 on 2023-03-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersstatistic',
            name='contact_link',
        ),
        migrations.AddField(
            model_name='usersstatistic',
            name='find',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Started searching'),
        ),
        migrations.AddField(
            model_name='usersstatistic',
            name='search',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Started executing the request'),
        ),
    ]
