# Generated by Django 4.1.7 on 2023-03-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0002_apartment_date'),
        ('statistic', '0002_remove_usersstatistic_contact_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Views')),
                ('favorite', models.IntegerField(blank=True, default=0, null=True, verbose_name='Add to favorite')),
                ('contact', models.IntegerField(blank=True, default=0, null=True, verbose_name='View agent contact')),
                ('find_date', models.DateTimeField(blank=True, null=True, verbose_name='Last view in find')),
                ('favorite_date', models.DateTimeField(blank=True, null=True, verbose_name='Last add in favorite')),
                ('apart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appart.apartment', verbose_name='Date upload and Unique ID apartment')),
            ],
        ),
    ]
