# Generated by Django 4.1.7 on 2023-03-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0002_apartment_date'),
        ('statistic', '0004_alter_apartstatistic_apart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartstatistic',
            name='apart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appart.apartment', verbose_name='Date upload and Unique ID apartment'),
        ),
    ]
