# Generated by Django 4.1.7 on 2023-03-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appart', '0002_apartment_date'),
        ('statistic', '0005_alter_apartstatistic_apart'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRUPStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first', models.IntegerField(blank=True, default=0, null=True, verbose_name='less than 10 mln')),
                ('second', models.IntegerField(blank=True, default=0, null=True, verbose_name='10 mln - 20 mln')),
                ('third', models.IntegerField(blank=True, default=0, null=True, verbose_name='20 mln - 30 mln')),
                ('fourth', models.IntegerField(blank=True, default=0, null=True, verbose_name='30 mln - 40 mln')),
                ('fifth', models.IntegerField(blank=True, default=0, null=True, verbose_name='40 mln - 50 mln')),
                ('sixth', models.IntegerField(blank=True, default=0, null=True, verbose_name='more than 50 mln')),
            ],
        ),
        migrations.CreateModel(
            name='PriceUSDStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first', models.IntegerField(blank=True, default=0, null=True, verbose_name='Less than 650')),
                ('second', models.IntegerField(blank=True, default=0, null=True, verbose_name='650 - 1300$')),
                ('third', models.IntegerField(blank=True, default=0, null=True, verbose_name='1300 - 1950$')),
                ('fourth', models.IntegerField(blank=True, default=0, null=True, verbose_name='1950 - 2600$')),
                ('fifth', models.IntegerField(blank=True, default=0, null=True, verbose_name='2600 - 3250$')),
                ('sixth', models.IntegerField(blank=True, default=0, null=True, verbose_name='more than 3250$')),
            ],
        ),
        migrations.RenameModel(
            old_name='UsersStatistic',
            new_name='CommonStatistic',
        ),
        migrations.CreateModel(
            name='LocationStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('index', models.IntegerField(blank=True, default=0, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appart.location')),
            ],
        ),
        migrations.CreateModel(
            name='AdsStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('daily', models.IntegerField(blank=True, default=0, null=True, verbose_name='New ads per day')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='All ads')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.locationstatistic', verbose_name='Location statistic')),
                ('price_rup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.pricerupstatistic', verbose_name='Price Rupiah statistic')),
                ('price_usd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.priceusdstatistic', verbose_name='Price USD statistic')),
            ],
        ),
    ]
