# Generated by Django 4.1.7 on 2023-03-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0006_pricerupstatistic_priceusdstatistic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsstatistic',
            name='location',
        ),
        migrations.RemoveField(
            model_name='adsstatistic',
            name='price_rup',
        ),
        migrations.RemoveField(
            model_name='adsstatistic',
            name='price_usd',
        ),
    ]
