# Generated by Django 4.1.7 on 2023-03-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0007_remove_adsstatistic_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationstatistic',
            name='location',
        ),
        migrations.AlterField(
            model_name='locationstatistic',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='locationstatistic',
            name='index',
            field=models.TextField(blank=True, null=True, verbose_name='Location'),
        ),
    ]
