# Generated by Django 4.1.7 on 2023-03-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(unique=True)),
                ('text_in_russian', models.TextField()),
                ('text_in_english', models.TextField()),
                ('text_in_indonesian', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
