# Generated by Django 4.1.7 on 2023-03-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts_in_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text_in_indonesian',
            field=models.TextField(blank=True, null=True),
        ),
    ]
